# Usa a imagem oficial do Node.js para build
FROM node:20 AS build

WORKDIR /app

# Copia os arquivos do projeto Angular
COPY . .

# Instala dependências e compila o projeto
RUN npm install && npm run build

# Segunda etapa: imagem final com Nginx
FROM nginx:alpine

# Remove a configuração padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos compilados do Angular
COPY --from=build /app/dist/frontend /usr/share/nginx/html

# Copia uma configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Expõe a porta do frontend
EXPOSE 80

# Inicia o servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
