name: Continuous Integration

on:
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main

jobs:
  CI-Pipeline:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SPRING_PROFILES_ACTIVE=prod" >> .env

      - name: Start Docker Compose
        run: docker-compose up --build -d --wait

      - name: Check Docker logs (if fails)
        if: failure()
        run: docker-compose logs --tail=100

      - name: Run health check
        run: curl --retry 10 --retry-delay 5 --fail http://localhost:8080/actuator/health || exit 1

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
